# print(len(input('enter your name')))
# n=input("enter some data :")
# print(n)

city=input("Enter the name of your city ")
print("/n",city)
petName=input("Enter the name of your pet animal ")
print(petName)
print("/n Your band name")
print(city+' '+petName)